// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6E4PvO7nTm3tOxakxOvG19B1IAVRPII',
    appId: '1:482105615588:android:3fbcc4f3cc70a1b33538f1',
    messagingSenderId: '482105615588',
    projectId: 'babytrack-3e123',
    storageBucket: 'babytrack-3e123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVR839EFF8AB56RPeBigRNf_t0XxxP2g',
    appId: '1:482105615588:ios:a232a49c77aa58df3538f1',
    messagingSenderId: '482105615588',
    projectId: 'babytrack-3e123',
    storageBucket: 'babytrack-3e123.firebasestorage.app',
    iosBundleId: 'fr.yoni.babytrack',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyQbtOKu3f9bd6mAL4axxoJ_yxnFgQq8',
    appId: '1:482105615588:web:3d04a3cfed1e64c53538f1',
    messagingSenderId: '482105615588',
    projectId: 'babytrack-3e123',
    storageBucket: 'babytrack-3e123.firebasestorage.app',
    authDomain: 'babytrack-3e123.firebaseapp.com',
    databaseURL: 'https://babytrack-3e123-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVR839EFF8AB56RPeBigRNf_t0XxxP2g',
    appId: '1:482105615588:ios:a232a49c77aa58df3538f1',
    messagingSenderId: '482105615588',
    projectId: 'babytrack-3e123',
    storageBucket: 'babytrack-3e123.firebasestorage.app',
    iosBundleId: 'fr.yoni.babytrack',
  );
}
